### ISSUE TITLE
Add .data prefix to calls with tidy evaluation

### ISSUE THREAD

**Issue by Bisaloo** [epiverse-trace/sivirep#10]
Most tidyverse functions use tidy evaluation, also called non-standard evaluation. This means that you don't use quotes to refer to something, even though this something is not an object in your R environment. For example:

```r
# standard evaluation
library("ggplot2")

# non-standard evaluation. This should normally fail because we didn't define any object called "ggplot2". But it works due to some programming tricks inside the library() function
library(ggplot2)
```

In the case of dplyr, this takes the following form:

```r
cars %>%
  # Note the absence of quotes around speed even though it's not a real object
  dplyr::filter(speed > 10)
```
The problem is that this will generate notes in `R CMD check`:

> no visible binding for global variable ...

The proper solution, as documented in [the vignette 'Programming with dplyr'](https://dplyr.tidyverse.org/articles/programming.html), and as [documented by Maëlle Salmon in the RStudio community forum](https://community.rstudio.com/t/how-to-solve-no-visible-binding-for-global-variable-note/28887/3), is to use the `.data` prefix:

```r
cars %>%
  dplyr::filter(.data$speed > 10)
```

**Comment by GeraldineGomez** [comment]
Hi @Bisaloo thank you very much for the observation and the documentation, that was already solved in the package.
