### ISSUE TITLE
agregar columna cod_eve a la función lista_eventos

### ISSUE THREAD

**Issue by zmcucunuba** [epiverse-trace/sivirep#105]
Geral. Podrías por favor agregar una columna de **cod_eve** a la funcion `lista_eventos`? 
No es urgente, pero es bastante útil tenerla allí
Gracias!

**Comment by GeraldineGomez** [comment]
Buen día Zulma,

Muchas gracias por tu contribución.  🚀🙏😊

El código del evento ya se puede obtener en el listado, puedes visualizarlo en el README y en la página web del paquete.

![image](https://github.com/user-attachments/assets/af19ecf9-7c28-4cf9-9bd7-fc8f2d42538f)
