### ISSUE TITLE
Fix examples in `cleaning_data.R`

### ISSUE THREAD

**Issue by Bisaloo** [epiverse-trace/sivirep#11]
The examples in `cleaning_data.R` all fail because the data you are cleaning has not been defined beforehand. For example, in:

https://github.com/epiverse-trace/sivirep/blob/29eab59c8853775575827687adb57798856eb847/R/cleaning_data.R#L8-L9

you need to define `deptos_data`.

**Comment by GeraldineGomez** [comment]
Hi @Bisaloo this was resolved, thanks!
