### ISSUE TITLE
Hardcoded path to malaria files

### ISSUE THREAD

**Issue by Bisaloo** [epiverse-trace/sivirep#12]
Not 100% sure but it looks like you have hardcoded a path, which means that malaria data will be fetched in `import_data_endemic_channel()`, no matter what the user passes as `disease_name`:

https://github.com/epiverse-trace/sivirep/blob/29eab59c8853775575827687adb57798856eb847/R/import_data.R#L57

**Comment by GeraldineGomez** [comment]
Hi @Bisaloo, thank you very much for the observation, that hardcoded path has already been eliminated, an apology for answering until now
