### ISSUE TITLE
Reporte grafico final

### ISSUE THREAD

**Issue by Oscarcasas92** [epiverse-trace/sivirep#145]
Respecto a la generación grafica, cuando se seleccione solo un municipio se podria visualizar todo el departamento y sombrear especificamente el municipio, para no ser redundante en graficas de este tipo:
![Captura de pantalla 2024-04-25 111844](https://github.com/epiverse-trace/sivirep/assets/62342833/8662f229-7e82-48ab-873c-26c8fac755a0)

Por otra parte seria interesante ver análisis comparativos entre departamentos al permitir seleccionar mas de una opción en esta variable.

**Comment by GeraldineGomez** [comment]
Hola @Oscarcasas92 ,

Muchas gracias por tus comentarios y sugerencias.

Implementar esta mejora en el mapa permitiría dar mayor claridad y entendimiento a los usuarios. La estaré implementando en los próximos días.

**Comment by GeraldineGomez** [comment]
Hola @Oscarcasas92,

Para notificarte que se han efectuado el ajuste y la mejora al mapa que propusiste para los municipios en el PR #168. Si deseas probarlo puedes remover `sivirep` y volverlo a instalar ejecutando los siguientes comandos:

``` r 
remove.packages("sivirep")
pak::pak("epiverse-trace/sivirep")
```

También quiero solicitar tu autorización para poner tu nombre y cuenta de GitHub en la lista de Contributors del paquete.
