### ISSUE TITLE
Comentarios SIVIREP

### ISSUE THREAD

**Issue by chuguett** [epiverse-trace/sivirep#146]
Es una buena aproximación al análisis exploratorio de las bases publicas de Sivigila, algunas mejoras de "forma" incluyen:

Los ejes de edad son "grupos de edad" no edades simples.
Nombrar las gráficas en la parte superior.
La gráfica de fecha de notificación esta repetida con la gráfica de fecha por inicio de síntomas.  

Un cambio importante es que Dengue y Malaria se debe calcular sobre la población a riesgo que provee Ministerio de Salud  y no sobre población total de las proyecciones DANE.

Muchas gracias por el trabajo porque permite automatizar el proceso de análisis descriptivo de históricos.

**Comment by GeraldineGomez** [comment]
Hola @chuguett, 

Muchas gracias por tus comentarios y recomendaciones 😊😊😊

Procederemos a separar cada una de las mejoras solicitadas en diferentes issues con el fin de generar trazabilidad en la historia de GitHub. Te estaremos notificando la resolución de los mismos.

**Comment by GeraldineGomez** [comment]
Hola @chuguett,

Estos ítems ya fueron resueltos en el PR #168:

- Los ejes de edad son "grupos de edad" no edades simples.
- La gráfica de fecha de notificación esta repetida con la gráfica de fecha por inicio de síntomas.

**Comment by GeraldineGomez** [comment]
Buen día @chuguett,

Todos los ítems fueron resueltos a través de la creación de otros issues y los siguientes PR:
-  #168
- #173
-
Muchas gracias!

**Comment by GeraldineGomez** [comment]
Buen día @chuguett,

Todos los ítems fueron resueltos a través de la creación de otros issues y los siguientes PR:
-  #168
- #173
Muchas gracias!
