### ISSUE TITLE
Prepare for CRAN release

### ISSUE THREAD

**Issue by Bisaloo** [epiverse-trace/sivirep#149]
I have not reviewed the package code or design but upon a cursory look, here are the points that almost surely will cause issues with CRAN:

- [x] the package is too large (>= 5MB):
  - some data is duplicated across `data` and `inst/extdata`, can this be fixed?
  - can a subset of the dengue2020 dataset be used in examples? Examples are just here to demonstrate the function usage, it's not so important if the result is not necessarily meaningful from a scientific point of view. Vignettes are here to fill this gap.
  - the `getting_started.Rmd` and `sivirep.Rmd` vignettes seem mostly duplicated (both leading to an almost 50MB HTML file)
  - I would convert the gif to webm, which is widely supported by all web browsers now ([source](https://caniuse.com/webm)): I achieved a 20x file size reduction doing this (with ffmpeg). Please let me know if you'd like me to submit a PR with this change
- [x] examples take too long
  - this should be improved automatically if you follow the smaller example dataset recommendation above
  - longer examples should be wrapped in \donttest{} 
- [x] the package is in Spanish. This is not a problem in itself but it's uncommon enough that CRAN is likely to raise an eyebrow over this. I would pre-empt any comments by explaining in `cran-comments.md` to scope of the package, why it has to be in Spanish, and how you have tried to follow recommendation from the official 'Writing R Extensions' guide: https://cran.r-project.org/doc/manuals/R-exts.html#The-DESCRIPTION-file-1

**Comment by GeraldineGomez** [comment]
Hi @Bisaloo, thanks for your review 😊:

-  the package is too large (>= 5MB):
    -  I'm currently working on reducing the size of `dengue2020`. I've addressed this in issue #133, but I've also created a separate issue #150 to highlight this concern for reviewers' convenience.
    - Yes, it's possible to remove the duplicated `data`.
    -  Please proceed with the PR for converting to `webm`.
    - I'll check the vignettes.
- examples take too long:
    - I've wrapped some longer examples in` \dontrun{}`. I'll evaluate which functions to implement ` \donttest{}` in or replace `\dontrun{}`.
-  Thank you for bringing up this point.  We'll provided a detailed explanation of the package's scope and why Spanish is necessary for its users and NIH needs.

**Comment by GeraldineGomez** [comment]
Hi @Bisaloo,

The issue related to the size of the dengue2020 dataset was resolved in PR #167; now its weight is 4.7 KB

**Comment by GeraldineGomez** [comment]
Hi Hugo,

The package is now avaliable on CRAN and the items mentioned above have been resolved.

Huge thanks to all of you for your collaboration and support in this journey 😊🚀🙏.

I'll proceed to close this issue.
