### ISSUE TITLE
Error when rendering PDF

### ISSUE THREAD

**Issue by jpavlich** [epiverse-trace/sivirep#159]
## Comportamiento Esperado
Render PDF de la información de una enfermedad, año y departamento especificados.

## Comportamiento Actual
Error

## Pasos a Reproducir
secuencia de pasos que se requieren para poder reproducir el defecto. Si en la ejecución del escenario usted hizo uso de algún dato, debe detallar en los pasos, que dato uso y en donde lo uso.
1. Verificar que en el archivo PruebasPDF.Rmd (o cualquier nombre que se le haya dado al archivo) del template del reporte la línea 15 sea 
 	- \usepackage[spanish]{babel}
2. Crear el reporte al ejecutar:
library(tinytex)
rmarkdown::render("PruebasPDF/PruebasPDF.Rmd", params = list(
  nombre_evento = "Malaria",
  year = 2017,
  departmento = "Choco"
))
3. Esperar hasta el final de la ejecución, pues el error se obtiene al final.

## Evidencias
! Package babel Error: Unknown option 'spanish'. Either you misspelled it
(babel)                or the language definition file spanish.ldf
(babel)                was not found.
(babel)                There is a locale ini file for this language.
(babel)                If it’s the main language, try adding `provide=*'
(babel)                to the babel package options.

Error: LaTeX failed to compile PruebasPDF.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See PruebasPDF.log for more info.
Además: There were 50 or more warnings (use warnings() to see the first 50)

## Contexto (Ambiente de Ejecución)
En esta sección se debe detallar el contexto en el que fue ejecutado el escenario de prueba.
- Se probó en Windows 11 23H2
- R versión 4.3.2
- RStudio version 2023.12.1 Build 402

## Información Adicional
Solución:
En la línea 15 del archivo PruebasPDF.Rmd donde inicialmente se tenía:
  - \usepackage[spanish]{babel}
reemplazar por:
  - \usepackage[spanish, provide=*]{babel}

A pesar de no obtener error, se obtienen más de 50 warnings

![image](https://github.com/epiverse-trace/sivirep/assets/1485744/88c96b2c-e0ff-43f3-ac3e-21f961f46bda)

Esto fue reportado por: @juanitaromerog

**Comment by GeraldineGomez** [comment]
Hi Jaime, 

Thank you for tackling this issue 😊🚀🙏. 

It was necessary to include this change in the full package review to meet the package's schedule. Therefore, I merged this change into the branch, referencing this issue and the solution you implemented. The solution has been tested, works correctly, and is now in the main branch. For that reason, I'll proceed to close this issue.
