### ISSUE TITLE
Chunk IDs must be in Spanish in the `report` template

### ISSUE THREAD

**Issue by jpavlich** [epiverse-trace/sivirep#166]

**Comment by GeraldineGomez** [comment]
Hi Jaime, 

Thank you for tackling this issue 😊🚀🙏. 

It was necessary to include this change in the full package review to meet the package's schedule. Therefore, I merged this change into the branch, referencing this issue and the solution you implemented. The solution has been tested, works correctly, and is now in the main branch. For that reason, I'll proceed to close this issue.
