### ISSUE TITLE
Broken image paths in vignette?

### ISSUE THREAD

**Issue by adamkucharski** [epiverse-trace/sivirep#195]
It looks like some of the image paths are [broken in the online page for automated reports](https://epiverse-trace.github.io/sivirep/articles/automated_report.html)?

**Comment by GeraldineGomez** [comment]
Hi @adamkucharski, thanks for reporting this. 

The paths are broken. I will review the image paths on the automated reports page and ensure they are fixed as soon as possible. I'll notify you once the issue is resolved.

**Comment by GeraldineGomez** [comment]
Hi @adamkucharski,

The image paths are now working correctly on the web page. Thanks!
