### ISSUE TITLE
epidemic channel

### ISSUE THREAD

**Issue by zmcucunuba** [epiverse-trace/sivirep#29]
Hi Gerald! Just before I forget, this is the typical visualisation for the endemic channel from Sivigila. Perhaps we need to work on this visualisation as a new feature for multi-year reports for both national and subnational. For the national, it would be ideal to have the plot for 32 departments at once. 

![image](https://github.com/epiverse-trace/sivirep/assets/22243967/7893f5de-2231-46f2-9697-b368fe9d4452)

**Comment by GeraldineGomez** [comment]
Hi Zulma!, as I mentioned to you before, we are going to integrate EpiCo to generate the endemic channel with @juan-umana. At the moment, this is the plot that EpiCo generates:

![image](https://github.com/epiverse-trace/sivirep/assets/46997659/5f0974e9-3687-490a-b264-0b0b3f1bf281)

The user only needs to provide the disease name, city or municipality code, and the year as parameters. By default, it produces the endemic channel using the geometric method. There are other parameters available that allow users to customize the endemic channel.

For national visualisation, I believe a good approach would be to create a dashboard or a link method. I'm going to explore other visualisation alternatives.

**Comment by zmcucunuba** [comment]
Hi @GeraldineGomez  and @juan-umana many thanks for this! Today we talked with Gerald about the circular dependency between sivirep and epico and so I think it's a great solution!
