### ISSUE TITLE
Add names od departments/municipalities into spatial_dept_dist functions

### ISSUE THREAD

**Issue by zmcucunuba** [epiverse-trace/sivirep#31]
`spatial_dept_dist <- group_dept(disease_data = clean_disease_data)`
is giving as output just **id** and   **casos**
```
spatial_dept_dist
# A tibble: 16 × 2
   id    casos
   <chr> <int>
 1 1         1
 2 5         5
 3 8         4
 4 15       19
```

can you please add *name of department*, to the output?
With this feature, the output becomes helpful for making tables. A similar feature for municipalities is needed. Thanks!

**Comment by GeraldineGomez** [comment]
Hi Zulma!, this an excellent suggestion, I will integrate this column into the dataframe, thanks!

**Comment by GeraldineGomez** [comment]
Hi Zulma,

This column has been added to the function, now the function is called `agrupar_dpto`, it includes the analysis by geo-occurrence and these are the results:

<img src="https://github.com/epiverse-trace/sivirep/assets/46997659/456f311c-48be-4348-a53b-de3a4431dc29" alt="drawing" width="400"/>

Furthermore, I have created another function called `agrupar_mpio` that produces the distribution of cases by municipalities:

<img src="https://github.com/epiverse-trace/sivirep/assets/46997659/4bb98dfd-6ed1-4385-b617-73cee13bf273" alt="drawing" width="600"/>
