### ISSUE TITLE
Avoid simulatenous dependency on dplyr and data.table

### ISSUE THREAD

**Issue by Bisaloo** [epiverse-trace/sivirep#62]
dplyr/tidyverse and data.table has mostly the same overall set of features and it's generally not necessary to depend on both.

To improve code maintainability and sustainability by avoiding unnecessary dependencies, it would be good to decide about using just one of them.

I suspect the dependency on data.table (only used twice: https://github.com/search?q=repo%3Aepiverse-trace%2Fsivirep+data.table%3A%3A&type=code) is currently weaker than the dependency on dplyr so it's probably easier to remove it.

**Comment by GeraldineGomez** [comment]
Hi @Bisaloo, this dependecy was removed in branch [fix-report-test](https://github.com/epiverse-trace/sivirep/tree/fix-report-test)
