### ISSUE TITLE
Código de departamento Error (Grupo 4) Sivirep

### ISSUE THREAD

**Issue by AntonioAlvaradoC** [epiverse-trace/sivirep#77]
En la creación del mapa de malaria, el codigo de departamento no se ve reflejado en el mapa.

En este, aparece el número de orden en la que aparecen los departamento de la tabla de descripción.

**Comment by GeraldineGomez** [comment]
Hola Antonio, 

Muchas gracias por generar la discusión respecto a este tema.

En el mapa se muestra el numero del índice asignado en la tabla de descripción, la cual esta ordenada alfabéticamente por cada departamento o municipio. Esto se debe a que algunos departamentos o regiones del mapa son muy pequeñas y su código es muy largo. Se diseño así para facilitar la visualización del mapa y para que no se sobrelapen los textos de los códigos unos con otros. En la tabla hay otra columna que se llama código departamento o municipio relacionada al índice, esto ayuda al usuario a conocer y validar el código del departamento o municipio si lo requiere.
