### ISSUE TITLE
Arrange the municipalities by number of cases

### ISSUE THREAD

**Issue by GAcero02** [epiverse-trace/sivirep#78]
It is recommended to organize municipalities by number of cases to improve understanding and decision making.

**Comment by GeraldineGomez** [comment]
Hi @GAcero02 ,

Many thanks for posting the improvement to the spatial distribution visualization bar. I'm going to create a branch to work on this enhancement.

**Comment by GeraldineGomez** [comment]
Hi @GAcero02 ,

This issue was resolved in the pull request #100.

Many thanks!
