### ISSUE TITLE
Creación de función para obtención de tiempo entre las fechas 

### ISSUE THREAD

**Issue by npinto22** [epiverse-trace/sivirep#79]
Si es posible incluir una función en donde se puedan obtener tiempos entre las fechas, por ejemplo, tiempo promedio entre fecha de inicio de síntomas y fecha de notificación, fecha de inicio de síntomas y fecha de defunción y fecha de inicio de síntomas y fecha de consulta. 

Aporte Grupo 4 Sivirep.

**Comment by GeraldineGomez** [comment]
Hola @npinto22 , 

Mil gracias por sugerir esta nueva funcionalidad en el paquete, estamos revisando el plan de trabajo para incluirla en el próximo release de `sivirep`. Cuando inicie su desarrollo crearemos un nuevo issue donde te incluiremos, en caso de que quieras contribuir directamente en su revisión o en el código fuente del paquete.
