### ISSUE TITLE
Add pkgdown reference index sections

### ISSUE THREAD

**Issue by Bisaloo** [epiverse-trace/sivirep#88]
sivirep currently provides many utility function to manipulate data provided by the SIVIGILA source.

As a result, the [pkgdown reference index](https://epiverse-trace.github.io/sivirep/reference/index.html) can be a bit overwhelming. It would be good to group the functions into logical sections, as [ggplot2 for example is doing](https://ggplot2.tidyverse.org/reference/index.html).

Your good design work makes it particularly easy here since you have use consistent function prefixes and names moulds throughout the package so you can just use selectors such as `starts_with()`.

Related pkgdown documentation: https://pkgdown.r-lib.org/reference/build_reference.html#reference-index

**Comment by GeraldineGomez** [comment]
Hi Hugo,

Thank you so much for the suggestion! 😊🚀🙏

I've included this change in PR #198.

- Commit reference: https://github.com/epiverse-trace/sivirep/commit/44c268181470cc53af1f5449aa70f94432dc7c1b
